#include <iostream>
#include "jeu_vie.hpp"

using namespace std; 

int main()
{
    cout << "*** Question 5 ***" << endl; 
    jeu_vie J_test(4,4); 
    cout << "Le nombre de voisins de la case (0,0) est " << J_test.voisins(0,0) << endl; //Output : 0.

    cout << "\n*** Question 8 ***" << endl; 
    ifstream fichier("planeur.txt"); 
    jeu_vie J(fichier);
    J.affichage(cout); 
    /* Output : 
    8 8
    ..X.....
    X.X.....
    .XX.....
    ........
    ........
    ........
    ........
    ........  */

    cout << "\n*** Question 9 ***" << endl; 
    for(int i = 0; i < 21; ++i)
    {
        cout << "État No. " << i << endl; 
        J.affichage(cout); 
        J.iteration(); 
    }
    /* Ouput : 
    État No. 0
    8 8
    ..X.....
    X.X.....
    .XX.....
    ........
    ........
    ........
    ........
    ........
    État No. 1
    8 8
    .X......
    ..XX....
    .XX.....
    ........
    ........
    ........
    ........
    ........

    ...
    ...

    État No. 20
    8 8
    ........
    ........
    ........
    ........
    ........
    .......X
    .....X.X
    ......XX  */

    cout << "\n*** Question 11 ***" << endl; 
    mt19937_64 G(time(nullptr)); 
    jeu_vie J_random(15,25,0.3,G); 
    for(int i = 0; i < 101; ++i)
    {
        J_random.iteration(); 
    }
    J_random.affichage(cout);
    /* Output : 
    15 25
    .........................
    .........................
    ..........X.X............
    .......XXX...X...........
    ......X..X......X........
    .......XX...XX..X........
    .............XX.X........
    .........................
    ................XXX......
    .............X...........
    ............X............
    .............XX..........
    .........................
    .........................
    ......................... */

    cout << "\n*** Question 13 ***" << endl; 
    for(double p= 0.; p<1; p+=0.1)
    {
        double moyenne =0.; 
        for(int j=0; j<100; j++)
        {
            jeu_vie J_iter(15,25,p,G); 
            for(int i=0; i<100; i++)
            {
                J_iter.iteration(); 
            }
            moyenne+=J_iter.nb_cellules();
        } 
        moyenne/=(double)100; 
        cout << "*** p = " << p << " *** : " << moyenne << endl; 
    }
    /* Output : 
    *** p = 0 *** : 0
    *** p = 0.1 *** : 9.7
    *** p = 0.2 *** : 20.88
    *** p = 0.3 *** : 22.8
    *** p = 0.4 *** : 22.17
    *** p = 0.5 *** : 22.49
    *** p = 0.6 *** : 18.17
    *** p = 0.7 *** : 12.28
    *** p = 0.8 *** : 3.85
    *** p = 0.9 *** : 0.36
    *** p = 1 *** : 0 */

    return 0; 
}